// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package dao

import (
	"github.com/google/uuid"
	"github.com/oddball707/recipes/model"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRecipeDAO creates a new instance of MockRecipeDAO. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRecipeDAO(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRecipeDAO {
	mock := &MockRecipeDAO{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRecipeDAO is an autogenerated mock type for the RecipeDAO type
type MockRecipeDAO struct {
	mock.Mock
}

type MockRecipeDAO_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRecipeDAO) EXPECT() *MockRecipeDAO_Expecter {
	return &MockRecipeDAO_Expecter{mock: &_m.Mock}
}

// CreateRecipe provides a mock function for the type MockRecipeDAO
func (_mock *MockRecipeDAO) CreateRecipe(recipe *model.Recipe) error {
	ret := _mock.Called(recipe)

	if len(ret) == 0 {
		panic("no return value specified for CreateRecipe")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*model.Recipe) error); ok {
		r0 = returnFunc(recipe)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRecipeDAO_CreateRecipe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateRecipe'
type MockRecipeDAO_CreateRecipe_Call struct {
	*mock.Call
}

// CreateRecipe is a helper method to define mock.On call
//   - recipe *model.Recipe
func (_e *MockRecipeDAO_Expecter) CreateRecipe(recipe interface{}) *MockRecipeDAO_CreateRecipe_Call {
	return &MockRecipeDAO_CreateRecipe_Call{Call: _e.mock.On("CreateRecipe", recipe)}
}

func (_c *MockRecipeDAO_CreateRecipe_Call) Run(run func(recipe *model.Recipe)) *MockRecipeDAO_CreateRecipe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *model.Recipe
		if args[0] != nil {
			arg0 = args[0].(*model.Recipe)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRecipeDAO_CreateRecipe_Call) Return(err error) *MockRecipeDAO_CreateRecipe_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRecipeDAO_CreateRecipe_Call) RunAndReturn(run func(recipe *model.Recipe) error) *MockRecipeDAO_CreateRecipe_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteRecipe provides a mock function for the type MockRecipeDAO
func (_mock *MockRecipeDAO) DeleteRecipe(id uuid.UUID) error {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteRecipe")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) error); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRecipeDAO_DeleteRecipe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteRecipe'
type MockRecipeDAO_DeleteRecipe_Call struct {
	*mock.Call
}

// DeleteRecipe is a helper method to define mock.On call
//   - id uuid.UUID
func (_e *MockRecipeDAO_Expecter) DeleteRecipe(id interface{}) *MockRecipeDAO_DeleteRecipe_Call {
	return &MockRecipeDAO_DeleteRecipe_Call{Call: _e.mock.On("DeleteRecipe", id)}
}

func (_c *MockRecipeDAO_DeleteRecipe_Call) Run(run func(id uuid.UUID)) *MockRecipeDAO_DeleteRecipe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRecipeDAO_DeleteRecipe_Call) Return(err error) *MockRecipeDAO_DeleteRecipe_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRecipeDAO_DeleteRecipe_Call) RunAndReturn(run func(id uuid.UUID) error) *MockRecipeDAO_DeleteRecipe_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllRecipes provides a mock function for the type MockRecipeDAO
func (_mock *MockRecipeDAO) GetAllRecipes() ([]*model.Recipe, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAllRecipes")
	}

	var r0 []*model.Recipe
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]*model.Recipe, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []*model.Recipe); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Recipe)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRecipeDAO_GetAllRecipes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllRecipes'
type MockRecipeDAO_GetAllRecipes_Call struct {
	*mock.Call
}

// GetAllRecipes is a helper method to define mock.On call
func (_e *MockRecipeDAO_Expecter) GetAllRecipes() *MockRecipeDAO_GetAllRecipes_Call {
	return &MockRecipeDAO_GetAllRecipes_Call{Call: _e.mock.On("GetAllRecipes")}
}

func (_c *MockRecipeDAO_GetAllRecipes_Call) Run(run func()) *MockRecipeDAO_GetAllRecipes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRecipeDAO_GetAllRecipes_Call) Return(recipes []*model.Recipe, err error) *MockRecipeDAO_GetAllRecipes_Call {
	_c.Call.Return(recipes, err)
	return _c
}

func (_c *MockRecipeDAO_GetAllRecipes_Call) RunAndReturn(run func() ([]*model.Recipe, error)) *MockRecipeDAO_GetAllRecipes_Call {
	_c.Call.Return(run)
	return _c
}

// GetRecipe provides a mock function for the type MockRecipeDAO
func (_mock *MockRecipeDAO) GetRecipe(id uuid.UUID) (*model.Recipe, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetRecipe")
	}

	var r0 *model.Recipe
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) (*model.Recipe, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) *model.Recipe); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Recipe)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRecipeDAO_GetRecipe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRecipe'
type MockRecipeDAO_GetRecipe_Call struct {
	*mock.Call
}

// GetRecipe is a helper method to define mock.On call
//   - id uuid.UUID
func (_e *MockRecipeDAO_Expecter) GetRecipe(id interface{}) *MockRecipeDAO_GetRecipe_Call {
	return &MockRecipeDAO_GetRecipe_Call{Call: _e.mock.On("GetRecipe", id)}
}

func (_c *MockRecipeDAO_GetRecipe_Call) Run(run func(id uuid.UUID)) *MockRecipeDAO_GetRecipe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRecipeDAO_GetRecipe_Call) Return(recipe *model.Recipe, err error) *MockRecipeDAO_GetRecipe_Call {
	_c.Call.Return(recipe, err)
	return _c
}

func (_c *MockRecipeDAO_GetRecipe_Call) RunAndReturn(run func(id uuid.UUID) (*model.Recipe, error)) *MockRecipeDAO_GetRecipe_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateRecipe provides a mock function for the type MockRecipeDAO
func (_mock *MockRecipeDAO) UpdateRecipe(recipe *model.Recipe) error {
	ret := _mock.Called(recipe)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRecipe")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*model.Recipe) error); ok {
		r0 = returnFunc(recipe)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRecipeDAO_UpdateRecipe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateRecipe'
type MockRecipeDAO_UpdateRecipe_Call struct {
	*mock.Call
}

// UpdateRecipe is a helper method to define mock.On call
//   - recipe *model.Recipe
func (_e *MockRecipeDAO_Expecter) UpdateRecipe(recipe interface{}) *MockRecipeDAO_UpdateRecipe_Call {
	return &MockRecipeDAO_UpdateRecipe_Call{Call: _e.mock.On("UpdateRecipe", recipe)}
}

func (_c *MockRecipeDAO_UpdateRecipe_Call) Run(run func(recipe *model.Recipe)) *MockRecipeDAO_UpdateRecipe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *model.Recipe
		if args[0] != nil {
			arg0 = args[0].(*model.Recipe)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRecipeDAO_UpdateRecipe_Call) Return(err error) *MockRecipeDAO_UpdateRecipe_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRecipeDAO_UpdateRecipe_Call) RunAndReturn(run func(recipe *model.Recipe) error) *MockRecipeDAO_UpdateRecipe_Call {
	_c.Call.Return(run)
	return _c
}
